// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublisherData;

#nullable disable

namespace PublisherData.migrations
{
    [DbContext(typeof(PubContext))]
    [Migration("20230109144715_authoridchange")]
    partial class authoridchange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "Rodrigo",
                            LastName = "Cortés"
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = "Brandon",
                            LastName = "Sanderson"
                        },
                        new
                        {
                            AuthorId = 3,
                            FirstName = "Javier",
                            LastName = "Negrete"
                        },
                        new
                        {
                            AuthorId = 4,
                            FirstName = "Joe",
                            LastName = "Abercrombie"
                        },
                        new
                        {
                            AuthorId = 5,
                            FirstName = "Stephen",
                            LastName = "King"
                        },
                        new
                        {
                            AuthorId = 6,
                            FirstName = "Arturo",
                            LastName = "Pérez Reverte"
                        },
                        new
                        {
                            AuthorId = 12,
                            FirstName = "Arturo",
                            LastName = "González Campos"
                        },
                        new
                        {
                            AuthorId = 7,
                            FirstName = "BB",
                            LastName = "King"
                        },
                        new
                        {
                            AuthorId = 8,
                            FirstName = "JRR",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            AuthorId = 9,
                            FirstName = "Christopher",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            AuthorId = 10,
                            FirstName = "Dean",
                            LastName = "Koontz"
                        },
                        new
                        {
                            AuthorId = 11,
                            FirstName = "Juan",
                            LastName = "Gómez Jurado"
                        });
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 2,
                            BasePrice = 0m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "El Imperio Final"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 12,
                            BasePrice = 0m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Enhorabuena por tu Fracaso"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 11,
                            BasePrice = 0m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cicatriz"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 11,
                            BasePrice = 0m,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "El Espía de Dios"
                        });
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.HasOne("PublisherDomain.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
